### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by okkhoy** [sds-edu/SDS-REST-API-MongoDB-Guide#1]
@sevenseasofbri @myc37 - please see the comments below and update the guide as necessary.

0. You don't mention which IDE you used or students can use. However, you mention "You do so via the IDE ..." at a few places. At the beginning pls mention which IDE do you suggest/did you use when developing this guide.
1. What is "endpoint"? (Section [REST API Conventions](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#rest-api-conventions))
    - It is quite well known, but it would help to add a glossary to tell what is an end point
 2. Give example for "Typically takes 2 URI per resource ..." (same section as above)
 3. What is "collections"? (same section)
 4. Make [repo ](https://github.com/CS3219-AY2324S1/SE-Toolbox-REST-API-MongoDB) public (Section: [Fork and clone ...](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#1-fork-and-clone-the-starter-repository))
 5. Specify where the dependencies are listed in [Install required dependencies](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#2-install-the-required-dependencies).
 6. Pls change: "You can create this file in the backend directory that you just created by following these steps:" -> "You can create this file in the backend directory that you just created by running `npm init`. The steps are as follows." (section: [Initialize package.json...](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#2-initialise-the-packagejson-file))
 7. In [Section for dependencies](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#3-install-the-required-dependencies), can we not specify these in a requirements file (or equivalent) rather than asking them to run the installation commands -- actually no harm in asking them to install it; but I thought it may be easier to give it in the requirements. -- for your consideration - not mandatory to fix
 8. Put this line "Make sure to read the inline comments to gain a better understanding of how the Express.js server works." before the code snippet in [Set up Express.js server](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#4-set-up-expressjs-server).
 9. Section -[ start backend](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#5-start-up-the-backend): explicitly mention there is more code instead of `...` in the code snippet (Or add a comment to say more/other code here)
 10. Remove the note about MongoDB atlas in [initialize .env for envi variables](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#2-initialise-env-file-for-environmental-variables). This is the only place you mention about Atlas (without specifying what is it, how to set it up etc.). So to avoid confusion, pls remove that note.
 11. Put this line: "Make sure to read the inline comments to gain a better understanding of how setting up a connection to MongoDB works." before the code snippet in [initialize the DB](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#3-initialise-the-database-and-connect-to-it).
 12. In the code snippet following this line: "Now, you will need to make use of this connectDB function in the backend entrypoint index.js. Make the following changes to index.js to connect to the MongoDB database when starting up the backend server:"
    - can you highlight the updated line using bold (or color or something like that)? OR
    - can you specify a few lines around and show the update? remove the rest of the file that looks similar. (similar to [define API route in post](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#define-api-route-1)) 
13. Typo in [Implementing REST API](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#implementing-rest-api). `structor` -> `structure`
14. In [define API route](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#define-api-route), the code snippet following "Then, you can add the following to index.js to connect the newly created address router" please state what is the newly added code (or similar to above suggestion, just show only the updated part of the code and say 'add this to the index.js'.
15. In the postman examples (particularly [for post](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-1)) please specify what should go as a part of the POST request in postman (annotating the image works too!)
16. Same as above [for Put](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-2).
17. When you are testing the [updating address ](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-2) and [deleting using postman](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-3), please specify the id you obtained in post. After post you make a forward reference in the TIP, but never refer it where it is necessary 🙂 
18. Where is AddressCardList.jsx created? First reference appears in [Fetching all address in frontend](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#fetch-all-addresses). Please state if they should create the file here OR specify earlier that this file needs to be created. Same with InputButton.jsx 
19. In [updating an existing address (frontend)](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#update-an-existing-address), pls move the line "Use this code snippet as a starting point to implement a way for users to update the existing addresses displayed in AddressCardList." above the code snippet
20. Same as above for [deleting an existing address](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#delete-an-existing-address).
21. [Additional resources](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#additional-resources) -> References

**Comment by sevenseasofbri** [comment]
For my reference: 
- [x] You don't mention which IDE you used or students can use. However, you mention "You do so via the IDE ..." at a few places. At the beginning pls mention which IDE do you suggest/did you use when developing this guide.
- [x] What is "endpoint"? (Section [REST API Conventions](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#rest-api-conventions))
    - It is quite well known, but it would help to add a glossary to tell what is an end point
- [x]  Give example for "Typically takes 2 URI per resource ..." (same section as above)
- [x] What is "collections"? (same section)
- [ ] Make [repo ](https://github.com/CS3219-AY2324S1/SE-Toolbox-REST-API-MongoDB) public (Section: [Fork and clone ...](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#1-fork-and-clone-the-starter-repository))
- [x] Specify where the dependencies are listed in [Install required dependencies](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#2-install-the-required-dependencies).
- [x]  Pls change: "You can create this file in the backend directory that you just created by following these steps:" -> "You can create this file in the backend directory that you just created by running `npm init`. The steps are as follows." (section: [Initialize package.json...](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#2-initialise-the-packagejson-file))
- [ ]  In [Section for dependencies](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#3-install-the-required-dependencies), can we not specify these in a requirements file (or equivalent) rather than asking them to run the installation commands -- actually no harm in asking them to install it; but I thought it may be easier to give it in the requirements. -- for your consideration - not mandatory to fix
- [x]  Put this line "Make sure to read the inline comments to gain a better understanding of how the Express.js server works." before the code snippet in [Set up Express.js server](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#4-set-up-expressjs-server).
- [x] Section -[ start backend](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#5-start-up-the-backend): explicitly mention there is more code instead of `...` in the code snippet (Or add a comment to say more/other code here)
- [x] Remove the note about MongoDB atlas in [initialize .env for envi variables](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#2-initialise-env-file-for-environmental-variables). This is the only place you mention about Atlas (without specifying what is it, how to set it up etc.). So to avoid confusion, pls remove that note.
- [x] Put this line: "Make sure to read the inline comments to gain a better understanding of how setting up a connection to MongoDB works." before the code snippet in [initialize the DB](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#3-initialise-the-database-and-connect-to-it).
- [x]  In the code snippet following this line: "Now, you will need to make use of this connectDB function in the backend entrypoint index.js. Make the following changes to index.js to connect to the MongoDB database when starting up the backend server:"
    - can you highlight the updated line using bold (or color or something like that)? OR
    - can you specify a few lines around and show the update? remove the rest of the file that looks similar. (similar to [define API route in post](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#define-api-route-1)) 
- [x]  Typo in [Implementing REST API](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#implementing-rest-api). `structor` -> `structure`
- [x]  In [define API route](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#define-api-route), the code snippet following "Then, you can add the following to index.js to connect the newly created address router" please state what is the newly added code (or similar to above suggestion, just show only the updated part of the code and say 'add this to the index.js'.
- [x]  In the postman examples (particularly [for post](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-1)) please specify what should go as a part of the POST request in postman (annotating the image works too!)
- [x]  Same as above [for Put](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-2).
- [x]  When you are testing the [updating address ](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-2) and [deleting using postman](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#test-api-route-3), please specify the id you obtained in post. After post you make a forward reference in the TIP, but never refer it where it is necessary 🙂 
- [x] Where is AddressCardList.jsx created? First reference appears in [Fetching all address in frontend](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#fetch-all-addresses). Please state if they should create the file here OR specify earlier that this file needs to be created. Same with InputButton.jsx 
- [x]  In [updating an existing address (frontend)](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#update-an-existing-address), pls move the line "Use this code snippet as a starting point to implement a way for users to update the existing addresses displayed in AddressCardList." above the code snippet
- [x]  Same as above for [deleting an existing address](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#delete-an-existing-address).
- [x]  [Additional resources](https://github.com/nus-CS3219/CS3219-REST-API-MongoDB-Guide/tree/merged-fixes-after-feedback#additional-resources) -> References
